# Use the official Golang image to build the Go application
FROM golang:1.22-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Build the Go app
RUN go build -o /hydra

# Start a new stage from scratch
FROM alpine:3.20

RUN <<HEREDOC
    apk add --no-cache --upgrade ca-certificates

    # Add a user/group for nonroot with a stable UID + GID. Values are from nonroot from distroless
    # for interoperability with other containers.
    addgroup --system --gid 65532 nonroot
    adduser --system --uid 65532 \
      --gecos "nonroot User" \
      --home /home/nonroot \
      --ingroup nonroot \
      --shell /sbin/nologin \
      nonroot
HEREDOC

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /hydra /usr/bin/hydra

USER nonroot

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
